// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNF7VvhVDEp21ND-E6GJy4HpS01XAo5_U',
    appId: '1:984112335409:web:5823b6fc1c17971be1e310',
    messagingSenderId: '984112335409',
    projectId: 'telemetry-555a6',
    authDomain: 'telemetry-555a6.firebaseapp.com',
    storageBucket: 'telemetry-555a6.appspot.com',
    measurementId: 'G-E99P7FWG3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyKvl05jKE0O9tiKPL1MQVrJCd0yyavC8',
    appId: '1:984112335409:android:b635f2e3ac575904e1e310',
    messagingSenderId: '984112335409',
    projectId: 'telemetry-555a6',
    storageBucket: 'telemetry-555a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Hgy0ZBbo0g4V8MlDYwXaZrWuLMyFM2o',
    appId: '1:984112335409:ios:9d4edcba0a91ba4be1e310',
    messagingSenderId: '984112335409',
    projectId: 'telemetry-555a6',
    storageBucket: 'telemetry-555a6.appspot.com',
    iosClientId: '984112335409-j967ss4uh10q55psnf99c43kkdkr72nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.telemetry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Hgy0ZBbo0g4V8MlDYwXaZrWuLMyFM2o',
    appId: '1:984112335409:ios:9d4edcba0a91ba4be1e310',
    messagingSenderId: '984112335409',
    projectId: 'telemetry-555a6',
    storageBucket: 'telemetry-555a6.appspot.com',
    iosClientId: '984112335409-j967ss4uh10q55psnf99c43kkdkr72nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.telemetry',
  );
}
